// 10 NPC-uri hardcodate care trăiesc o săptămână în Iași
// Fiecare are schedule complet (7 zile × 8 module), relații, personalitate

export const NPC_INITIALI = [
  // ─────────────────────────────────────────────────────────────
  // 1. ANDREI POPA — student 21
  // ─────────────────────────────────────────────────────────────
  {
    id: 1,
    nume: 'Andrei Popa',
    varsta: 21,
    profesie: 'Student',
    personalitate: 'energic, sociabil, procrastinator incurabil',
    relatii: {
      'Radu Georgescu': 'prieten_bun',
      'Elena Vasile': 'prieten',
      'Raluca Stan': 'coleg_de_facultate',
    },
    schedule: {
      Luni: {
        early_morning:    'dormit',
        late_morning:     'facultate',
        early_afternoon:  'cantina',
        late_afternoon:   'facultate',
        early_evening:    'biblioteca',
        late_evening:     'cafea_cu_prietenii',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'dormit',
        late_morning:     'facultate',
        early_afternoon:  'cantina',
        late_afternoon:   'biblioteca',
        early_evening:    'sala_fitness',
        late_evening:     'gaming_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'dormit',
        late_morning:     'facultate',
        early_afternoon:  'cantina',
        late_afternoon:   'facultate',
        early_evening:    'fotbal_cu_prietenii',
        late_evening:     'bere_dupa_fotbal',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'dormit',
        late_morning:     'facultate',
        early_afternoon:  'cantina',
        late_afternoon:   'biblioteca',
        early_evening:    'acasa',
        late_evening:     'gaming_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'dormit',
        late_morning:     'facultate',
        early_afternoon:  'masa_cu_colegii',
        late_afternoon:   'liber',
        early_evening:    'pregatit_iesire',
        late_evening:     'club',
        early_night:      'club',
        late_night:       'club',
      },
      Sambata: {
        early_morning:    'dormit',
        late_morning:     'dormit',
        early_afternoon:  'trezit_masa_acasa',
        late_afternoon:   'plimbare_copou',
        early_evening:    'cinema',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'trezit_lenes',
        early_afternoon:  'masa_la_parinti',
        late_afternoon:   'plimbare_copou',
        early_evening:    'teme_acasa',
        late_evening:     'teme_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 2. ELENA VASILE — programatoare 28
  // ─────────────────────────────────────────────────────────────
  {
    id: 2,
    nume: 'Elena Vasile',
    varsta: 28,
    profesie: 'Programatoare',
    personalitate: 'introvertita, analitica, pasionata de open-source',
    relatii: {
      'Andrei Popa': 'prieten',
      'Bogdan Marin': 'coleg_de_munca',
      'Raluca Stan': 'prietena_buna',
    },
    schedule: {
      Luni: {
        early_morning:    'cafea_acasa',
        late_morning:     'munca_remote',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'munca_remote',
        early_evening:    'curs_online',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'alergat_copou',
        late_morning:     'munca_birou',
        early_afternoon:  'masa_cu_colegii',
        late_afternoon:   'munca_birou',
        early_evening:    'cumparaturi',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'cafea_acasa',
        late_morning:     'munca_remote',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'munca_remote',
        early_evening:    'proiect_personal',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'alergat_copou',
        late_morning:     'munca_birou',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'meeting_echipa',
        early_evening:    'proiect_personal',
        late_evening:     'film_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'cafea_acasa',
        late_morning:     'munca_birou',
        early_afternoon:  'masa_cu_Andrei',
        late_afternoon:   'munca_birou',
        early_evening:    'iesire_cu_Raluca',
        late_evening:     'restaurant',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'alergat_copou',
        late_morning:     'cafea_cafenea',
        early_afternoon:  'proiect_personal',
        late_afternoon:   'cumparaturi',
        early_evening:    'gatit_acasa',
        late_evening:     'film_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'trezit_lenes',
        early_afternoon:  'cafenea_citit',
        late_afternoon:   'proiect_personal',
        early_evening:    'gatit_acasa',
        late_evening:     'relaxare',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 3. DR. MIHAI IONESCU — medic 45
  // ─────────────────────────────────────────────────────────────
  {
    id: 3,
    nume: 'Dr. Mihai Ionescu',
    varsta: 45,
    profesie: 'Medic Chirurg',
    personalitate: 'pragmatic, dedicat, rar se relaxeaza',
    relatii: {
      'Prof. Ioana Constantin': 'prieten_vechi',
      'Alexandru Dima': 'cunostinta',
    },
    schedule: {
      Luni: {
        early_morning:    'trezit_cafea',
        late_morning:     'consultatie_spital',
        early_afternoon:  'operatie_spital',
        late_afternoon:   'consultatie_spital',
        early_evening:    'acasa',
        late_evening:     'citit_medicinal',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'trezit_cafea',
        late_morning:     'consultatie_spital',
        early_afternoon:  'masa_spital',
        late_afternoon:   'operatie_spital',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'garda_spital',
        late_morning:     'garda_spital',
        early_afternoon:  'garda_spital',
        late_afternoon:   'garda_spital',
        early_evening:    'garda_spital',
        late_evening:     'garda_spital',
        early_night:      'garda_spital',
        late_night:       'garda_spital',
      },
      Joi: {
        early_morning:    'dormit_dupa_garda',
        late_morning:     'dormit_dupa_garda',
        early_afternoon:  'trezit_masa',
        late_afternoon:   'plimbare_copou',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'trezit_cafea',
        late_morning:     'consultatie_spital',
        early_afternoon:  'masa_cu_Ioana',
        late_afternoon:   'consultatie_spital',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'alergat_dimineata',
        late_morning:     'acasa',
        early_afternoon:  'masa_familie',
        late_afternoon:   'gradina',
        early_evening:    'acasa',
        late_evening:     'film_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'acasa',
        early_afternoon:  'masa_familie',
        late_afternoon:   'plimbare_familie',
        early_evening:    'acasa',
        late_evening:     'pregatit_saptamana',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 4. PROF. IOANA CONSTANTIN — profesor 52
  // ─────────────────────────────────────────────────────────────
  {
    id: 4,
    nume: 'Prof. Ioana Constantin',
    varsta: 52,
    profesie: 'Profesor Universitar',
    personalitate: 'metodica, rabdatoare, pasionata de cultura',
    relatii: {
      'Dr. Mihai Ionescu': 'prieten_vechi',
      'Gheorghe Lupu': 'vecin',
    },
    schedule: {
      Luni: {
        early_morning:    'trezit_cafea',
        late_morning:     'cursuri_universitate',
        early_afternoon:  'masa_universitate',
        late_afternoon:   'cursuri_universitate',
        early_evening:    'corectat_lucrari',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'trezit_cafea',
        late_morning:     'office_hours',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'sedinta_departament',
        early_evening:    'corectat_lucrari',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'trezit_cafea',
        late_morning:     'cursuri_universitate',
        early_afternoon:  'masa_universitate',
        late_afternoon:   'cursuri_universitate',
        early_evening:    'acasa',
        late_evening:     'pregatit_curs',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'trezit_cafea',
        late_morning:     'cursuri_universitate',
        early_afternoon:  'masa_cu_Mihai',
        late_afternoon:   'office_hours',
        early_evening:    'corectat_lucrari',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'trezit_cafea',
        late_morning:     'cursuri_universitate',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'liber_biblioteca',
        early_evening:    'plimbare_copou',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'trezit_gradina',
        late_morning:     'piata_hala',
        early_afternoon:  'gatit',
        late_afternoon:   'citit',
        early_evening:    'concert_filarmonica',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'biserica',
        late_morning:     'plimbare_copou',
        early_afternoon:  'masa_familie',
        late_afternoon:   'citit',
        early_evening:    'pregatit_saptamana',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 5. CRISTI POPESCU — bucatar 35
  // ─────────────────────────────────────────────────────────────
  {
    id: 5,
    nume: 'Cristi Popescu',
    varsta: 35,
    profesie: 'Bucătar Șef',
    personalitate: 'pasionat, haios, temperamental in bucatarie',
    relatii: {
      'Raluca Stan': 'prieten_bun',
      'Gheorghe Lupu': 'cunostinta',
    },
    schedule: {
      Luni: {
        early_morning:    'piata_centrala',
        late_morning:     'pregatit_restaurant',
        early_afternoon:  'servit_clienti',
        late_afternoon:   'servit_clienti',
        early_evening:    'inchis_restaurant',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'piata_centrala',
        late_morning:     'pregatit_restaurant',
        early_afternoon:  'servit_clienti',
        late_afternoon:   'servit_clienti',
        early_evening:    'inchis_restaurant',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'liber_acasa',
        late_morning:     'piata_specii',
        early_afternoon:  'gatit_experimente',
        late_afternoon:   'cafea_cu_Raluca',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'piata_centrala',
        late_morning:     'pregatit_restaurant',
        early_afternoon:  'servit_clienti',
        late_afternoon:   'servit_clienti',
        early_evening:    'inchis_restaurant',
        late_evening:     'bere_dupa_munca',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'piata_centrala',
        late_morning:     'pregatit_restaurant',
        early_afternoon:  'servit_clienti',
        late_afternoon:   'servit_clienti',
        early_evening:    'servit_clienti',
        late_evening:     'inchis_restaurant',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'piata_centrala',
        late_morning:     'pregatit_restaurant',
        early_afternoon:  'servit_clienti',
        late_afternoon:   'servit_clienti',
        early_evening:    'servit_clienti',
        late_evening:     'iesire_cu_Raluca',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'trezit_lenes',
        early_afternoon:  'gatit_acasa_pentru_placere',
        late_afternoon:   'plimbare_copou',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 6. RALUCA STAN — artista 26
  // ─────────────────────────────────────────────────────────────
  {
    id: 6,
    nume: 'Raluca Stan',
    varsta: 26,
    profesie: 'Artistă Plastică',
    personalitate: 'creativa, visatoare, traieste noaptea',
    relatii: {
      'Elena Vasile': 'prietena_buna',
      'Cristi Popescu': 'prieten_bun',
      'Andrei Popa': 'coleg_de_facultate',
    },
    schedule: {
      Luni: {
        early_morning:    'dormit',
        late_morning:     'cafea_inspiratie',
        early_afternoon:  'atelier_pictura',
        late_afternoon:   'atelier_pictura',
        early_evening:    'plimbare_inspiratie',
        late_evening:     'atelier_noaptea',
        early_night:      'atelier_noaptea',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'dormit',
        late_morning:     'trezit_cafea',
        early_afternoon:  'atelier_pictura',
        late_afternoon:   'atelier_pictura',
        early_evening:    'expozitie_palatul_culturii',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'dormit',
        late_morning:     'cafea_cu_Cristi',
        early_afternoon:  'atelier_pictura',
        late_afternoon:   'atelier_pictura',
        early_evening:    'centrul_vechi_inspiratie',
        late_evening:     'atelier_noaptea',
        early_night:      'atelier_noaptea',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'dormit',
        late_morning:     'trezit_cafea',
        early_afternoon:  'atelier_pictura',
        late_afternoon:   'intalnire_galerie',
        early_evening:    'iesire_cu_Elena',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'dormit',
        late_morning:     'trezit_cafea',
        early_afternoon:  'atelier_pictura',
        late_afternoon:   'atelier_pictura',
        early_evening:    'vernisaj_expozitie',
        late_evening:     'petrecere_dupa_vernisaj',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'dormit',
        late_morning:     'trezit_lenes',
        early_afternoon:  'piata_obiecte_vintage',
        late_afternoon:   'atelier_pictura',
        early_evening:    'iesire_cu_Cristi',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'dormit',
        early_afternoon:  'trezit_cafea',
        late_afternoon:   'atelier_pictura',
        early_evening:    'plimbare_copou',
        late_evening:     'atelier_noaptea',
        early_night:      'atelier_noaptea',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 7. ALEXANDRU DIMA — avocat 38
  // ─────────────────────────────────────────────────────────────
  {
    id: 7,
    nume: 'Alexandru Dima',
    varsta: 38,
    profesie: 'Avocat',
    personalitate: 'ambitios, pragmatic, mereu in grafic',
    relatii: {
      'Bogdan Marin': 'partener_de_afaceri',
      'Dr. Mihai Ionescu': 'cunostinta',
    },
    schedule: {
      Luni: {
        early_morning:    'trezit_stiri',
        late_morning:     'tribunal',
        early_afternoon:  'masa_rapida',
        late_afternoon:   'client_consultatie',
        early_evening:    'dosar_cabinet',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'trezit_stiri',
        late_morning:     'client_consultatie',
        early_afternoon:  'masa_cu_Bogdan',
        late_afternoon:   'tribunal',
        early_evening:    'dosar_cabinet',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'trezit_stiri',
        late_morning:     'tribunal',
        early_afternoon:  'masa_rapida',
        late_afternoon:   'tribunal',
        early_evening:    'networking_eveniment',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'trezit_stiri',
        late_morning:     'client_consultatie',
        early_afternoon:  'masa_rapida',
        late_afternoon:   'negocieri_contract',
        early_evening:    'dosar_cabinet',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'trezit_stiri',
        late_morning:     'tribunal',
        early_afternoon:  'masa_restaurant',
        late_afternoon:   'client_consultatie',
        early_evening:    'acasa',
        late_evening:     'iesire_cu_familia',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'dormit',
        late_morning:     'golf_club',
        early_afternoon:  'masa_restaurant_cu_familia',
        late_afternoon:   'acasa',
        early_evening:    'acasa',
        late_evening:     'film_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'acasa',
        early_afternoon:  'masa_familie',
        late_afternoon:   'dosar_cabinet',
        early_evening:    'acasa',
        late_evening:     'pregatit_saptamana',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 8. BOGDAN MARIN — antreprenor 33
  // ─────────────────────────────────────────────────────────────
  {
    id: 8,
    nume: 'Bogdan Marin',
    varsta: 33,
    profesie: 'Antreprenor Tech',
    personalitate: 'workaholic, optimist, mereu pe telefon',
    relatii: {
      'Alexandru Dima': 'partener_de_afaceri',
      'Elena Vasile': 'coleg_de_munca',
    },
    schedule: {
      Luni: {
        early_morning:    'email_cafea',
        late_morning:     'meeting_echipa',
        early_afternoon:  'masa_rapida_birou',
        late_afternoon:   'pitch_investitori',
        early_evening:    'birou',
        late_evening:     'email_acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'email_cafea',
        late_morning:     'meeting_clienti',
        early_afternoon:  'masa_cu_Alexandru',
        late_afternoon:   'birou',
        early_evening:    'networking',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'email_cafea',
        late_morning:     'birou',
        early_afternoon:  'masa_rapida_birou',
        late_afternoon:   'meeting_investitori',
        early_evening:    'networking_eveniment',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'email_cafea',
        late_morning:     'birou',
        early_afternoon:  'masa_cu_parteneri',
        late_afternoon:   'birou',
        early_evening:    'birou_tarziu',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'email_cafea',
        late_morning:     'meeting_saptamanal',
        early_afternoon:  'masa_restaurant',
        late_afternoon:   'birou',
        early_evening:    'acasa',
        late_evening:     'relaxare',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'dormit',
        late_morning:     'email_cafea',
        early_afternoon:  'birou_proiecte',
        late_afternoon:   'sport_sala',
        early_evening:    'iesire_seara',
        late_evening:     'restaurant',
        early_night:      'acasa',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'acasa_lenes',
        early_afternoon:  'masa_familie',
        late_afternoon:   'strategie_saptamana',
        early_evening:    'acasa',
        late_evening:     'relaxare',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 9. RADU GEORGESCU — sportiv 24
  // ─────────────────────────────────────────────────────────────
  {
    id: 9,
    nume: 'Radu Georgescu',
    varsta: 24,
    profesie: 'Sportiv Profesionist (Handbal)',
    personalitate: 'disciplinat, competitiv, strict cu dieta',
    relatii: {
      'Andrei Popa': 'prieten_bun',
      'Bogdan Marin': 'cunostinta',
    },
    schedule: {
      Luni: {
        early_morning:    'antrenament_dimineata',
        late_morning:     'recuperare_masaj',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'antrenament_tehnic',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'antrenament_dimineata',
        late_morning:     'sala_echipa',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'meci_antrenament',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'antrenament_dimineata',
        late_morning:     'liber_recuperare',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'fotbal_cu_Andrei',
        early_evening:    'bere_dupa_fotbal',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'antrenament_dimineata',
        late_morning:     'sala_echipa',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'antrenament_tehnic',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'antrenament_dimineata',
        late_morning:     'sala_echipa',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'pregatire_meci',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'incalzire_meci',
        late_morning:     'meci_oficial',
        early_afternoon:  'masa_echipa',
        late_afternoon:   'recuperare',
        early_evening:    'iesire_cu_Andrei',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'dormit',
        late_morning:     'alergat_copou',
        early_afternoon:  'masa_proteica',
        late_afternoon:   'acasa',
        early_evening:    'acasa',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 10. GHEORGHE LUPU — pensionar 68
  // ─────────────────────────────────────────────────────────────
  {
    id: 10,
    nume: 'Gheorghe Lupu',
    varsta: 68,
    profesie: 'Pensionar (Fost Profesor de Matematică)',
    personalitate: 'intelepciune calma, nostalgic, iubeste traditiile',
    relatii: {
      'Prof. Ioana Constantin': 'vecin',
      'Cristi Popescu': 'cunostinta',
    },
    schedule: {
      Luni: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'piata_hala',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'gradina',
        early_evening:    'televizor',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Marti: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'plimbare_copou',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'sah_cu_prietenii',
        early_evening:    'televizor',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Miercuri: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'piata_hala',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'gradina',
        early_evening:    'televizor',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Joi: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'medic_control',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'plimbare_copou',
        early_evening:    'vizita_nepoti',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Vineri: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'piata_hala',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'cafea_vechi_prieteni',
        early_evening:    'televizor',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Sambata: {
        early_morning:    'trezit_devreme_cafea',
        late_morning:     'plimbare_lunga_copou',
        early_afternoon:  'masa_acasa',
        late_afternoon:   'gradina',
        early_evening:    'televizor',
        late_evening:     'acasa',
        early_night:      'dormit',
        late_night:       'dormit',
      },
      Duminica: {
        early_morning:    'biserica',
        late_morning:     'plimbare_dupa_biserica',
        early_afternoon:  'masa_cu_familia',
        late_afternoon:   'gradina',
        early_evening:    'televizor',
        late_evening:     'citit',
        early_night:      'dormit',
        late_night:       'dormit',
      },
    },
  },
];
